name: execute linters and tests
on: pull_request 

jobs:
  ci-backend: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Run linter on backend
        run: npm run lint
        

  ci-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Run linter on frontend
        run: npm run lint
